import test from 'node:test';
import assert from 'node:assert/strict';
import { mcheynePlan, getMcheyneReadings } from '../data/mcheyne.js';
import { getReadingPlan, getReadings, normaliseReadingPlan, readingPlans } from '../data/reading-plans.js';
import { buildOffice } from '../src/office.js';
import { getYearLectionary, lessonSummary } from '../src/year-calendar.js';
import { chaptersFromReference, getYearCoverage } from '../src/year-coverage.js';

test('M’Cheyne dataset contains exactly 365 unique calendar appointments', () => {
  assert.equal(Object.keys(mcheynePlan).length, 365);
  assert.ok(Object.values(mcheynePlan).every(day => Array.isArray(day) && day.length === 4 && day.every(Boolean)));
});

test('M’Cheyne 1 January preserves Family then Secret split', () => {
  const date = new Date(2026, 0, 1);
  assert.deepEqual(getMcheyneReadings(date, 'morning'), { first:'Genesis 1', second:'Matthew 1' });
  assert.deepEqual(getMcheyneReadings(date, 'evening'), { first:'Ezra 1', second:'Acts 1' });
});

test('M’Cheyne key dates match the published calendar', () => {
  assert.deepEqual(getMcheyneReadings(new Date(2026, 7, 17), 'morning'), { first:'1 Samuel 9', second:'Romans 7' });
  assert.deepEqual(getMcheyneReadings(new Date(2026, 7, 17), 'evening'), { first:'Jeremiah 46', second:'Psalm 22' });
  assert.deepEqual(getMcheyneReadings(new Date(2026, 11, 31), 'evening'), { first:'Malachi 4', second:'John 21' });
});

test('M’Cheyne leap day is explicit catch-up rather than a shifted plan', () => {
  const leap = getMcheyneReadings(new Date(2028, 1, 29), 'morning');
  assert.equal(leap.first, null);
  assert.match(leap.note, /catch-up day/i);
  assert.deepEqual(getMcheyneReadings(new Date(2028, 2, 1), 'morning'), { first:'Exodus 12:21-50', second:'Luke 15' });
});

test('changing reading plan does not change Psalter or collects', () => {
  const date = new Date(2026, 7, 17);
  const bcp = buildOffice(date, 'morning', '1662');
  const mch = buildOffice(date, 'morning', 'mcheyne');
  assert.deepEqual(mch.psalms, bcp.psalms);
  assert.deepEqual(mch.collects, bcp.collects);
  assert.notDeepEqual(mch.lessons, bcp.lessons);
});

test('annual M’Cheyne view is generated by the same reading engine', () => {
  const row = getYearLectionary(2026, 'mcheyne').find(r => r.date.getMonth() === 7 && r.date.getDate() === 17);
  assert.equal(lessonSummary(row.morning), '1 Samuel 9 · Romans 7');
  assert.equal(lessonSummary(row.evening), 'Jeremiah 46 · Psalm 22');
});

test('M’Cheyne chapter coverage reaches the complete 66-book canon', () => {
  const coverage = getYearCoverage(2026, 'mcheyne');
  assert.equal(coverage.canonicalChapters, 1189);
  assert.equal(coverage.percent, 100);
  assert.equal(coverage.includesApocrypha, false);
});

test('coverage parser handles verse ranges, cross-chapter ranges and disjoint chapters', () => {
  assert.deepEqual(chaptersFromReference('Luke 1:1-38'), ['Luke 1']);
  assert.deepEqual(chaptersFromReference('Isaiah 8:1-9:7'), ['Isaiah 8','Isaiah 9']);
  assert.deepEqual(chaptersFromReference('Jeremiah 36&45'), ['Jeremiah 36','Jeremiah 45']);
});

test('Common Worship is architecturally present but cannot silently fall back', () => {
  assert.equal(readingPlans['common-worship'].available, false);
  assert.equal(normaliseReadingPlan('common-worship'), '1662');
  assert.throws(() => getReadings(new Date(2026,0,1), 'morning', 'common-worship'), /not available/i);
});

test('unknown stored plan safely normalises to 1662', () => {
  assert.equal(getReadingPlan('not-a-plan').id, '1662');
  assert.equal(normaliseReadingPlan('not-a-plan'), '1662');
});
